export { default as Header } from './Header'
export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as SkillsPage } from './SkillsPage'
export { default as ExpirencesPage } from './ExpirencesPage'